const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

const SIGNIN_REQUEST='SIGNIN_REQUEST';
const SIGNIN_SUCCESS='SIGNIN_SUCCESS';
const SIGNIN_FAIL='SIGNIN_FAIL';

const LOGGED_IN='LOGGED_IN';

const GET_USER_INFO_REQUEST='GET_USER_INFO_REQUEST';
const GET_USER_INFO_SUCCESS='GET_USER_INFO_SUCCESS';
const GET_USER_INFO_FAIL='GET_USER_INFO_FAIL';

const GET_LIST_GROUP_REQUEST='GET_LIST_GROUP_REQUEST';
const GET_LIST_GROUP_SUCCESS='GET_LIST_GROUP_SUCCESS';
const GET_LIST_GROUP_FAIL='GET_LIST_GROUP_FAIL';

const UPDATE_USER_REQUEST='UPDATE_USER_REQUEST';
const UPDATE_USER_SUCCESS='UPDATE_USER_SUCCESS';
const UPDATE_USER_FAIL='UPDATE_USER_FAIL';

const TOGGLE_REMEMBER_ME='TOGGLE_REMEMBER_ME';
const CURRENT_REMEMBER_ME='CURRENT_REMEMBER_ME';

const TOGGLE_UPDATE_FORM='TOGGLE_UPDATE_FORM';

const GET_GROUP_CURRENT='GET_GROUP_CURRENT';

const UPDATE_GROUP='UPDATE_GROUP';

const DELETE_GROUP_SUCCESS='DELETE_GROUP_SUCCESS';

const TOGGLE_CREATE_FORM='TOGGLE_CREATE_FORM';

const CREATE_GROUP_SUCCESS='CREATE_GROUP_SUCCESS';

const actionTypes = {
    OPEN_SIDEBAR,
    CLOSE_SIDEBAR,
    TOGGLE_SIDEBAR,

    REGISTER_USER_FAIL,
    REGISTER_USER_REQUEST,
    REGISTER_USER_SUCCESS,

    SIGNIN_FAIL,
    SIGNIN_REQUEST,
    SIGNIN_SUCCESS,

    LOGGED_IN,

    GET_USER_INFO_FAIL,
    GET_USER_INFO_REQUEST,
    GET_USER_INFO_SUCCESS,

    GET_LIST_GROUP_FAIL,
    GET_LIST_GROUP_REQUEST,
    GET_LIST_GROUP_SUCCESS,

    UPDATE_USER_FAIL,
    UPDATE_USER_REQUEST,
    UPDATE_USER_SUCCESS,

    TOGGLE_REMEMBER_ME,
    CURRENT_REMEMBER_ME,

    TOGGLE_UPDATE_FORM,
    GET_GROUP_CURRENT,

    UPDATE_GROUP,

    DELETE_GROUP_SUCCESS,
    CREATE_GROUP_SUCCESS,
    TOGGLE_CREATE_FORM

}

export default actionTypes;